### ISSUE TITLE
download the paper

### ISSUE THREAD

**Issue by lz-8713** [ChrisZonghaoLi/sky130_ldo_rl#1]
"Design and Optimization of Low-Dropout Voltage Regulator Using Relational Graph Neural Network and Reinforcement Learning in Open-Source SKY130 Process"  hello ，How to download this paper？

**Comment by ChrisZonghaoLi** [comment]
This paper is not available yet. I have it submitted to a conference and still waiting for the result. Once it gets accepted I will post the paper here.

**Comment by ChrisZonghaoLi** [comment]
Paper has been posted here.
